### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by Adriien-M** [st1s/angular-morris#55]
I wanted to use these undocumented options: `barGap `and `barSizeRatio`
It will be nice to include them in the options list...

Here is an exemple: [http://jsbin.com/nozabinoso/edit?html,js,output](url)

**Comment by stewones** [comment]
Hey @Adriien-M

I am planning to release a new version soon with some improves and this will be one. Thx

**Comment by pedrohsantana** [comment]
Hi @stewones !

What about **_select(index)_**? 
Are you planning to include it in next release? 

And when are yout planning to release it? =)

**Comment by stewones** [comment]
hey @pedrohsantana 
yes soon. no dates sry =(

anyway.. you can fork then make your workaround, commit and change your bower.json to use `your_user/angular-morris-chart`

**Comment by pedrohsantana** [comment]
Ok, tks Stewan!

 

Atenciosamente,

 




Pedro Henrique Santana

Consultoria em Projetos

+55 (34) 3014.2840 | (34) 9 8806.9625

4MM Inovações em Negócios | 4mm.com.br

 

 <http://www.droni.com.br/> 

 

De: Stewan Pacheco [mailto:notifications@github.com] 
Enviada em: segunda-feira, 8 de agosto de 2016 16:17
Para: stewones/angular-morris-chart <angular-morris-chart@noreply.github.com>
Cc: pedrohsantana <pedrohenrique@4mm.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [stewones/angular-morris-chart] Missing options (#55)

 

hey @pedrohsantana <https://github.com/pedrohsantana>  
yes soon. no dates sry =(

anyway.. you can fork then make your workaround, commit and change your bower.json to use your_user/angular-morris-chart

**Comment by sujeetpillai** [comment]
I submitted a pull-request for barGap and barSizeRatio. It's been merged to master. I believe this issue can be close.d

**Comment by st1s** [comment]
Hi @sujeetpillai 
make sense
thanks for the PR 😄
